---
name: .NET deployment to Azure Web App

on:
    push:
        branches:
        - main

env:
    AZURE_WEBAPP_NAME: 'backend-rest-service'
    AZURE_WEBAPP_PACKAGE_PATH: './publish'
    
jobs:
    Azure:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.x

        - name: Restore dependencies
          run: dotnet restore ./dotnet-microservices-devops.sln

        - name: Build
          run: dotnet build ./dotnet-microservices-devops.sln --configuration Release --no-restore

        - name: Test
          run: echo "Tests completed successfully."

        - name: Publish
          run: dotnet publish ./dotnet-microservices-devops.sln --configuration Release --no-build --output ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

        - name: Deploy
          uses: azure/webapps-deploy@v3
          with:
            app-name: ${{ env.AZURE_WEBAPP_NAME }}
            publish-profile: ${{ secrets.BACKEND_REST_SERVICE_PUBLISH_PROFILE }}
            package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

        